kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: node
    commands:
      - pwd
      - ls -al

  - name: scp files
    image: appleboy/drone-scp
    pull: true
    settings:
      host: 
        - foodmate-ws-api.tomas.website
      ssh_username:
        from_secret: ssh_username
      ssh_password: 
        from_secret: ssh_password
      password: 
        from_secret: ssh_password
      port: 22
      script:
        - echo "Hello World"
        - echo pwd
      # target: /var/www/html/foodmate-ws-api
      when:
        branch: master
      # source:
      #   - /tmp/008887463/7H8fCcf9UV.tar

  # - name: ssh commands
  #   image: appleboy/drone-ssh
  #   settings:
  #     when:
  #       branch: master
  #     host: 
  #       - foodmate-ws-api.tomas.website
  #     ssh_username:
  #       from_secret: ssh_username
  #     ssh_password: 
  #       from_secret: ssh_password
  #     password: 
  #       from_secret: ssh_password
  #     port: 22
  #     script:
  #       - . /root/.nvm/nvm.sh && nvm use 10.9.0
  #       - mkdir -p /var/www/html/orora-foodmate/foodmate-ws-api
  #       - cd /root/drone/src/github.com/orora-foodmate/foodmate-ws-api
  #       - yarn install
  #       - cp -a ./* /var/www/html/orora-foodmate/foodmate-ws-api
  #       - cd /root
  #       - rm -rf /root/drone
