pipeline:
  scp:
    image: appleboy/drone-scp
    pull: true
    host: 
      - foodmate-ws-api.tomas.website
    port: 22
    username: root
    user: root
    secrets: [ ssh_password ]
    target: /root
    source:
      - /drone/src/github.com/orora-foodmate/foodmate-ws-api
    when:
      branch: master

  ssh:
    image: appleboy/drone-ssh
    host: 
      - foodmate-ws-api.tomas.website
    username: root
    user: root
    secrets: [ ssh_password ]
    command_timeout: 600
    script:
      - . /root/.nvm/nvm.sh && nvm use 10.9.0
      - mkdir -p /var/www/html/orora-foodmate/foodmate-ws-api
      - cd /root/drone/src/github.com/orora-foodmate/foodmate-ws-api
      - yarn install
      - cp -a ./* /var/www/html/orora-foodmate/foodmate-ws-api
      - cd /root
      - rm -rf /root/drone
    when:
      branch: master