kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: scp files
    image: appleboy/drone-scp
    pull: true
    settings:
      host: 
        - foodmate-ws-api.tomas.website
      username: root
      secrets: [ ssh_password ]
      port: 22
      target: /root
      when:
        branch: master
      source:
        - /drone/src/github.com/orora-foodmate/foodmate-ws-api

  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      when:
        branch: master
      host: 
        - foodmate-ws-api.tomas.website
      username: root
      secrets: [ ssh_password ]
      port: 22
      script:
        - . /root/.nvm/nvm.sh && nvm use 10.9.0
        - mkdir -p /var/www/html/orora-foodmate/foodmate-ws-api
        - cd /root/drone/src/github.com/orora-foodmate/foodmate-ws-api
        - yarn install
        - cp -a ./* /var/www/html/orora-foodmate/foodmate-ws-api
        - cd /root
        - rm -rf /root/drone
